config/urls.py
from re import I
from xml.dom.minidom import Document
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from posts.views import index, url_view, url_parameter_view, function_view,class_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('url/', url_view),
    path('url/<str:username>/',url_parameter_view),
    path('fbv/', function_view),
    path('cbv/', class_view.as_view(), name='cbv'),

    path('', index, name='index'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('posts/', include('posts.urls', namespace='posts')),
    
    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .views import post_create_form_view, post_list_view, post_create_view, post_update_view, post_detail_view, post_delete_view

app_name = 'posts'
urlpatterns = [
    path('',post_list_view, name='post-list'),
    # path('new/',post_create_view, name='post-create'),
    path('new/',post_create_form_view, name='post-create'),
    path('<int:id>/',post_detail_view, name='post-detail'),
    path('<int:id>/edit/',post_update_view, name='post-update'),
    path('<int:id>/delete/',post_delete_view, name='post-delete'),
]

posts/models.py
from tkinter import CASCADE
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class Post(models.Model) :
    image = models.ImageField(verbose_name='이미지', null=True, blank=True)
    content = models.TextField(verbose_name= '내용')
    created_at = models.DateTimeField(verbose_name= '작성일', auto_now_add=True)
    view_count = models.IntegerField(verbose_name= '조회수', default=0)
    writer = models.ForeignKey(to=User, on_delete=models.CASCADE, null=True, blank=True)

class Comment(models.Model) :
    content = models.TextField(verbose_name= '내용')
    created_at = models.DateTimeField(verbose_name= '작성일',auto_now_add=True)
    post = models.ForeignKey(to='Post', on_delete=models.CASCADE)
    writer = models.ForeignKey(to=User, on_delete=models.CASCADE)

posts/forms.py
import imp
from sre_parse import CATEGORIES
from unicodedata import category
from django import forms
from .models import Post

# class PostBaseForm(forms.Form):
#     CATEGORY_CHOICES = [
#         ('1','일반'),
#         ('2','계정')
#     ]
#     iamge = forms.ImageField(label='이미지')
#     content = forms.CharField(label='내용', widget=forms.Textarea)
#     category = forms.ChoiceField(label='카테고리',choices=CATEGORY_CHOICES)

class PostBaseForm(forms.ModelForm):
    # forms.ModelForm 을 상속받을 때에는 class를 하나 더 만들어야 한다.
    class Meta :
        model = Post
        fields = '__all__'
        # models.py 의 Post class의 모든 필드가 적용이 된다.

from django.core.exceptions import ValidationError
class PostCreateForm(PostBaseForm):
    class Meta(PostBaseForm.Meta):
        fields = ['image','content']
    
    def clean_content(self):
        data = self.cleaned_data['content']
        if '비속어' == data:
            raise ValidationError("'비속어'는 사용할 수 없습니다.")
        return data

class PostUpdateForm(PostBaseForm):
    class Meta(PostBaseForm.Meta):
        fields = ['image','content']

class PostDetailForm(PostBaseForm):
    def __init__(self,*args,**kwargs):
        super(PostDetailForm,self).__init__(*args,**kwargs)
        for key in self.fields:
            self.fields[key].widget.attrs['disabled']=True
            # detail.html에서 {{form.as_p}} 부분을 주석처리 해뒀음!

posts/views.py
from csv import writer
from multiprocessing import context
from re import template
import re
from sys import orig_argv
from django.shortcuts import redirect, render, get_object_or_404
from django.http import Http404, HttpResponse, JsonResponse
from django.views.generic.list import ListView
from .models import Post
from django.contrib.auth.decorators import login_required
from .forms import PostBaseForm,PostCreateForm,PostDetailForm
# Create your views here.
def index(request) :
    post_list = Post.objects.all().order_by('-created_at')
    context = {
        'post_list': post_list,
    }
    return render(request, 'index.html',context)
    
def post_list_view(request) :
    post_list = Post.objects.all() #Post 전체 데이터 조회
    # post_list = Post.objects.filter(writer=request.user) #Post.writer가 현재 로그인인 것 조회
    context = {
        'post_list': post_list,
    }
    return render(request, 'posts/post_list.html',context)

def post_detail_view(request, id) :

    try :
        post = Post.objects.get(id=id) # 하나만 불러올거기 때문에 get 으로 불러온다.
    except Post.DoesNotExist:
        return redirect('index') # 주소에 id값을 다른걸 입력하게 되면 index로 넘어간다. - 에러가 나지 않게 하는 것
    context = {
        'post' : post,
        'form' : PostDetailForm,
    }
    return render(request, 'posts/post_detail.html', context)

@login_required
def post_create_view(request) :
    if request.method == "GET" :
        return render(request, 'posts/post_form.html')
    else :
        image = request.FILES.get('image')
        content = request.POST.get('content')
        print(image)
        print(content)
        Post.objects.create(
            image=image,
            content=content,
            writer=request.user,
        )
        return redirect('index')   

def post_create_form_view(request) :
    if request.method == "GET" :
        form = PostCreateForm()
        context = {'form' : form}
        return render(request, 'posts/post_form2.html', context)
    else :
        form = PostCreateForm(request.POST, request.FILES)
        
        if form.is_valid():
            Post.objects.create(
            image=form.cleaned_data['image'],
            content=form.cleaned_data['content'],
            writer=request.user,
        )
        else :
            return redirect('posts:post-create')        
        return redirect('index')  

@login_required
def post_update_view(request, id) : #create랑 detail이랑 합쳐졌다고 생각하면 된다. 그래서 POST랑 GET 둘 다 필요하다.
    
    # post = Post.objects.get(id=id)
    post = get_object_or_404(Post, id=id,writer=request.user)

    if request.method == "GET" :
        context = { 'post': post}
        return render(request, 'posts/post_form.html', context)
    elif request.method == "POST" :
        new_image = request.FILES.get('image')
        content = request.POST.get('content')
        print(new_image)
        print(content)
        if new_image :
            post.image.delete()
            post.image = new_image
        
        post.contene = content
        post. save()
        return redirect('posts:post-detail',post.id)

@login_required
def post_delete_view(request, id) :
    post = get_object_or_404(Post, id=id,writer=request.user)
    # if request.user != post.writer:
    #     raise Http404('잘못된 접근입니다.')
    
    if request.method == 'GET' :
        context = { 'post': post}
        return render(request, 'posts/post_confirm_delete.html', context)   
    else :
        post.delete()
        return redirect('index')
    









def url_view(request) :
    print('url_view()')
    data = {'code':'001', 'msg':'ok'}
    return HttpResponse('<h1>안녕</h1>')
    # return JsonResponse(data)

def url_parameter_view(request, username):
    print('url_parameter_view()')
    print(f'username: {username}')
    print(f'request.GET: {request.GET}')
    return HttpResponse(username)

def function_view(request) :
    print(f'request.method: {request.method}')

    if request.method =='GET' :
        print(f'request.GET: {request.GET}')
    elif request.method =='POST' :
        print(f'request.POST: {request.POST}')
    # print(f'request.GET: {request.GET}')  #GET = 데이터를 받을 때 사용
    # print(f'request.POST: {request.POST}') #POST = 데이터를 추가,수정,삭제 할 때 사용
    return render(request, 'view.html')

    # 이 위까지는 FBV 함수 기반 뷰
    # 밑에서부터는 CBV 클래스 기반 뷰

class class_view(ListView) :
    model = Post
    template_name = 'cbv_view.html'

templates/posts/post_confirm_delete.html
{% extends 'base.html' %}
{% block title %}글 삭제{% endblock %}

{% block content %}
<h1>Post 삭제 화면</h1>
<form action="" method="POST"> {% csrf_token %}
    <p>한 번 삭제된 데이터는 복구가 불가능 합니다.</p><br>
    <p>그래도 삭제하시겠습니까? ID : {{post.id }}</p><br>

    <a href="{% url 'index' %}">돌아가기</a>
    <input type="submit" value="삭제하기">
</form>
{% include 'mixin/post_card.html' with detail=True %}
{% endblock %}

templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}글 상세{% endblock %}

{% block content %}
<h1>Post 상세 화면</h1>
{% include 'mixin/post_card.html' with detail=True %}
    <!-- {{ form.as_p }} -->
<!-- post_card와 연결되는 부분
detail을 True 설정하고 post_card에서는 if not detail로 작성해서
detail에서는 더보기를 없애고 아니면 더보기를 보여준다. -->
{% endblock %}

templates/posts/post_form.html
{% extends 'base.html' %}
{% block title %}글 입력{% endblock %}

{% block content %}
<h1>Post 입력 화면</h1>
<form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}
    <div>
        <label for="id_image">이미지</label>
        {% if post.image %}
            <p>현재 : <a href="{{post.image.url}}">{{ post.image.name }}</a></p>
            <p>변경 : <input type="file" name="image" accept="image/*" id="id_image"></p>
        {% else %}
            <input type="file" name="image" accept="image/*" id="id_image">
        {% endif %}
    </div>
    <div>
        <label for="id_content">내용</label>
        <textarea name="content" id="id_content" cols="30" rows="10">{% if post%}{{ post.content }}{% endif %}</textarea>
        <!-- if는 안써줘도 되지만 정확하게 하기 위해서 써주는 것 -->
    </div>
    <div>
        <input type="submit" value="제출">
    </div>
</form>
{% endblock %}

templates/posts/post_form2.html
{% extends 'base.html' %}
{% block title %}글 입력{% endblock %}

{% block content %}
<h1>Post 입력 화면 - Form 사용</h1>
<form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}
    <div>
        {{ form.as_p }}
        <!-- 템플릿 태그의 주석과 html 자체 주석처리와 다른점!! -->
        <!-- html자체 주석처리는 지금 이 주석처리이고, 웹페이지에서 검사를 하면 태그가 보이긴한다! -->
        {# 하지만 템플릿태그로 주석처리를 하면 검사에서도 보이지 않게 된다!  요거 되게 신기하넹#}
    </div>
    <div>
        <input type="submit" value="제출">
    </div>
</form>
{% endblock %}

templates/posts/post_list.html
{% extends 'base.html' %}
{% block title %}글 목록{% endblock %}

{% block content %}
<h1>Post 목록 화면</h1>
<!-- {{ post_list }} -->
{% for post in post_list %}
    <div>
        {{post.id}}<br/>
        {{post.image}}<br/>
        {{post.content}}<br/>
        {{post.created_at}}<br/>
        {{post.writer}}<br/>
    </div>
{% endfor %}
{% endblock %}